version: '2'
services:
  postgres:
    image: postgres
    container_name: after
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=after
      - POSTGRES_USER=after
      - POSTGRES_PASSWORD=123
      - MAX_CONNECTIONS=300